name: use_external_packages
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Alexis Villegas Torres <email@example.com>

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
 http: "^0.11.3+16"
 path: "^1.6.0"

dev_dependencies:
  test: ^0.12.30
